### ISSUE TITLE
how to improve the reconstruction quality?

### ISSUE THREAD

**Issue by trltzy** [One-2-3-45/One-2-3-45#15]
Great work and the views are good, but sometimes the reconstruction is still a little bit coarse. Is there some parameters I can change to improve the reconstruction quality please? I saw thers is a finetune mode in SparseNeuS, can we use it here too? thx!

**Comment by Colin97** [comment]
Thank you for reaching out. The results are often limited by the multi-view generation, since there are 3D inconsistencies among the predicted views. In some cases, regenerating certain views can help. The fine-tune mode in SparseNeuS  typically doesn't enhance our outcomes also due to inherent inconsistencies in multi-view predictions. We're actively working on improving multi-view prediction and developing more robust lifting algorithms. Please stay tuned for updates.

**Comment by trltzy** [comment]
thanks, look forward to your enhancement!

**Comment by trltzy** [comment]
Hi, I tried some other samples as input(fig1), I got the model as fig2. Actually I found the view consistensy in 8*4=32views are good enough, and I want the result model more refined, with a higher resolution, how can I achieve this effect? the model now is a little bit coarse... Is this related with the SparseNeuS part? Thank you!

> fig1
![image](https://github.com/One-2-3-45/One-2-3-45/assets/67675349/05d504ed-7557-4786-be0b-f9e957de4d25)
fig2
![image](https://github.com/One-2-3-45/One-2-3-45/assets/67675349/5eac1560-7aa3-4cc6-9529-0151fbfa428f)

**Comment by Dustinpro** [comment]
We made improvements to both the multi-view generation and 3D reconstruction modules in [One-2-3-45++](https://sudo-ai-3d.github.io/One2345plus_page/), resulting in more consistent multi-view predictions and higher quality textured mesh.
