### ISSUE TITLE
Is that possible to generate more angle image?

### ISSUE THREAD

**Issue by r530044129** [One-2-3-45/One-2-3-45#18]
May I generate more image in different angle? 
In the stage2, i saw there are 32 images, may i generate 64/128/256/... at a the densy sample angles?
Just like scan the whole object in all the angle

**Comment by Haian-Jin** [comment]
Sure. In theory, using more images can help to achieve better performance. We didn't use more images in practice because of efficiency considerations.

I personally think you need to re-train the model if you want to generate more images during inference as the model got 32 images as source images during training.

**Comment by neomatrix25** [comment]
can you share the steps to train from scratch changing the number of camera angles.

**Comment by Colin97** [comment]
You can refer to [here](https://github.com/One-2-3-45/One-2-3-45/blob/3c82aa614fcb80924fddd14531056eda7e795aaa/utils/zero123_utils.py#L60) for predicting multi-view images with different camera angles. For training the reconstruction module, you may want to change the camera poses in [data loader](https://github.com/One-2-3-45/One-2-3-45/blob/3c82aa614fcb80924fddd14531056eda7e795aaa/reconstruction/data/One2345_train.py#L88) as well.
