### ISSUE TITLE
GPU utilization is relatively low when training 

### ISSUE THREAD

**Issue by NguyenTriTrinh** [One-2-3-45/One-2-3-45#22]
Firstly , Thanks for your great work!!
By the way, i have two problems when I tried to train the model using my datasets.  
1. During training, I noticed that the GPU utilization is relatively low. Are there any strategies or optimizations to increase GPU utilization for faster training?
2. When I modify `self.batch_size` in `exp_runner_generic_blender_train.py` from `self.batch_size = self.num_devices` to `self.batch_size = 2 * self.num_devices`, I encounter an error here：
 `  File “_/home/myu/One-2-3-45/reconstruction/models/trainer_generic.py_”, line 1300, in validate_mesh
    vertices = np.matmul(trans_mat_np, vertices_homo[:, :, None])[:, :3, 0]
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,4,4)->(2,newaxis,newaxis) (178616,4,1)->(178616,newaxis,newaxis)  and requested shape (4,1)` 

Could you please help me understand what might be causing this issue and how can i increase batch_sizes?

Thank you in advance for your assistance.

**Comment by Colin97** [comment]
1. We also encountered low GPU utilization during training, which is inherited from the SparseNeuS codebase. Unfortunately, we have not yet figured out a solution.

2. It seems that the original validation code doesn't generalize to multiple examples. @Haian-Jin, do you have any idea how to resolve the shape mismatch issue?

**Comment by Haian-Jin** [comment]
The training code is inherited from the SparseNeuS codebase. So like SparseNeuS, it can only construct one cost volume per iteration per GPU, and therefore it can only support setting batch size to be 1, as commented [here](https://github.com/One-2-3-45/One-2-3-45/blob/master/reconstruction/models/trainer_generic.py#L165). To support multiple shapes per iteration, you need to edit more code and only changing batch size won't work.

The error you mentioned seemed to be because the first dimension of the first tensor is 2 (not 1) but another tensor's first dimension is 178616, which means they are different and neither of them is 1, so they could not be broadcast.
